apiVersion: v1
kind: Pod
metadata:
  name: kafka-tools
spec:
  containers:
  - image: confluentinc/cp-zookeeper:6.1.0
    name: zookeeper
    ports:
      - containerPort: 2181
    env:
      - name: ZOOKEEPER_ID
        value: "1"
      - name: ZOOKEEPER_CLIENT_PORT
        value: "2181"
      - name: ZOOKEEPER_TICK_TIME
        value: "2000"
  - image: confluentinc/cp-kafka:6.1.0
    name: kafka1
    ports:
      - containerPort: 9092
    env:
      - name: KAFKA_BROKER_ID
        value: "1"
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: localhost:2181
      - name: KAFKA_ADVERTISED_LISTENERS
        value: EXTERNAL_LISTENER://kafka1:9092,INTERNAL_LISTENER://localhost:29092
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: EXTERNAL_LISTENER:PLAINTEXT,INTERNAL_LISTENER:PLAINTEXT
      - name: KAFKA_INTER_BROKER_LISTENER_NAME
        value: INTERNAL_LISTENER




  
  
